services:
  template-demo:
    build:
      context: .
      target: all
    env_file:
      - path: .env
        required: false
    develop:
      watch:
        - path: src
          action: rebuild
    restart: no
    profiles:
      - manual
    tty: true
    stdin_open: true
  template-demo-api:
    build:
      context: .
      target: slim
    env_file:
      - path: .env
        required: false
    develop:
      watch:
        - path: src
          action: rebuild
    command: system serve --host=0.0.0.0 --port=8000 --no-watch
    restart: always
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8000/healthz" ]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
      start_interval: 1s
  template-demo-notebook:
    build:
      context: .
      target: all
    env_file:
      - path: .env
        required: false
    develop:
      watch:
        - path: src
          action: rebuild
    command: notebook --host=0.0.0.0 --port=8001
    restart: always
    ports:
      - "8001:8001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8001/healthz" ]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
      start_interval: 1s
