name: "Test"

on:
  workflow_call:
    # No inputs needed at this time

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1
        with:
          version: "0.6.3"
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install dev tools
        shell: bash
        run: .github/workflows/_install_dev_tools.bash

      - name: Install Python, venv and dependencies
        run: uv sync --all-extras --frozen --link-mode=copy

      - name: Release version check
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          TOML_VERSION=$(uv run python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")
          if [ "$TAG_VERSION" != "$TOML_VERSION" ]; then
            echo "Release version mismatch: Tag $TAG_VERSION != pyproject.toml $TOML_VERSION"
            exit 1
          fi

      - name: Print development version info
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          TOML_VERSION=$(uv run python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")
          echo "Development build - Current version in pyproject.toml: $TOML_VERSION"

      - name: Create .env file
        uses: SpicyPizza/create-envfile@ace6d4f5d7802b600276c23ca417e669f1a06f6f # v2.0.3
        with:
          envkey_TEMPLATE_DEMO_LOGFIRE_TOKEN: "${{ secrets.TEMPLATE_DEMO_LOGFIRE_TOKEN }}"
          envkey_TEMPLATE_DEMO_SENTRY_DSN: "${{ secrets.TEMPLATE_DEMO_SENTRY_DSN }}"
          fail_on_empty: false

      - name: Validate installation
        run: |
            OUTPUT=$(uv run --no-dev template-demo --help)
            if [[ "$OUTPUT" != *"built with love in Berlin"* ]]; then
            echo "Output does not contain 'built with love in Berlin'"
            exit 1
            fi

      - name: Smoke tests
        run: |
          uv run --no-dev template-demo --help
          uv run --all-extras template-demo system info
          uv run --all-extras template-demo system health
      
      - name: Test / regular
        run: |
          set +e
          make test
          EXIT_CODE=$?
          # Show test execution in GitHub Job summary
          found_files=0
          for file in reports/pytest_*.md; do
          if [ -f "$file" ]; then
            cat "$file" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            found_files=1
          fi
          done
          if [ $found_files -eq 0 ]; then
            echo "# All regular tests passed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
          # Show test coverage in GitHub Job summary
          if [ -f "reports/coverage.md" ]; then
            cat "reports/coverage.md" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          else
            echo "# No test coverage computed." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
          exit $EXIT_CODE

      - name: Test / long running
        run: |
          set +e
          make test_long_running
          EXIT_CODE=$?
          # Show test execution in GitHub Job summary
          found_files=0
          for file in reports/pytest_*.md; do
          if [ -f "$file" ]; then
            cat "$file" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            found_files=1
          fi
          done
          if [ $found_files -eq 0 ]; then
            echo "# All long running tests passed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
          # Show test coverage in GitHub Job summary
          if [ -f "reports/coverage.md" ]; then
            cat "reports/coverage.md" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          else
            echo "# No test coverage computed." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
          exit $EXIT_CODE
      
      - name: Upload test results
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        if: ${{ always() && (env.GITHUB_WORKFLOW_RUNTIME != 'ACT') }}
        with:
          name: test-results
          path: |
            reports/mypy_junit.xml
            reports/junit.xml
            reports/coverage.xml
            reports/coverage.md
            reports/coverage_html
            template_demo.log
          retention-days: 30

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
        if: ${{ !cancelled() && (env.GITHUB_WORKFLOW_RUNTIME != 'ACT') }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: pavel-trunov/template-demo

      - name: Upload test results to Codecov
        if: ${{ !cancelled() && (env.GITHUB_WORKFLOW_RUNTIME != 'ACT') }}
        uses: codecov/test-results-action@f2dba722c67b86c6caa034178c6e4d35335f6706 # v1.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarQube Scan
        if: ${{ !cancelled() && (env.GITHUB_WORKFLOW_RUNTIME != 'ACT') }}
        uses: SonarSource/sonarqube-scan-action@0303d6b62e310685c0e34d0b9cde218036885c4d # v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
