name: "Scheduled Testing"

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  test-scheduled:
    uses: ./.github/workflows/_scheduled-test.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
